version: 2

models:
  - name: dim_devices
    description: "This view contains device related info from `stg_ga4__events` table." 
    columns:
      - name: event_id
        tests:
          - unique
          - not_null

      - name: device_category
        description: "The category of the device."
        tests:
          - not_null
          - accepted_values:
              values: ['mobile', 'desktop', 'tablet']
      
      - name: device_mobile_brand_name
        description: "The brand name of the mobile device."
        tests:
          - not_null

      - name: device_mobile_model_name
        description: "The model name of the mobile device."
        tests:
          - not_null

      - name: device_mobile_marketing_name
        description: "The marketing name of the mobile device."
        tests:
          - not_null

      - name: device_operating_system
        description: "The operating system of the device."

      - name: device_operating_system_version
        description: "The version of the operating system of the device."
        tests:
          - not_null

  - name: dim_locations
    description: "This view contains location related info from `stg_ga4__events` table."
    columns:
      - name: event_id

      - name: continent
        description: "The continent of the location."

      - name: sub_continent
        description: "The sub-continent of the location."

      - name: country
        description: "The country of the location."

      - name: region
        description: "The region of the location."

      - name: city
        description: "The city of the location."

      - name: metro
        description: "The metro of the location."

  - name: dim_traffic_sources
    description: "This view contains traffic source related info from `stg_ga4__events` table."
    columns:
      - name: event_id
        description: "The unique identifier for the event"
        tests:
          - not_null

      - name: traffic_category
        description: "The categorized traffic source"
        tests:
          - not_null
          - accepted_values:
              values: ['direct', 'organic_search', 'referral', 'paid_search', 'uncategorized', 'other']

      - name: traffic_source
        description: "The source of the traffic."

      - name: traffic_source_medium
        description: "The medium of the traffic."

      - name: traffic_source_name
        description: "The name of the traffic source."

      - name: traffic_source_campaign
        description: "The campaign of the traffic."

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - event_id
            - traffic_category
            - traffic_source_medium
            - traffic_source_name
            - traffic_source